name: Dockerized FastAPI Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      # Step 4: Install dependencies
      - name: Install dependencies
        run: poetry install

      # Step 5: Export environment variables for tests
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql+asyncpg://myuser:mypassword@localhost:5432/mydb" >> $GITHUB_ENV

      # Step 6: Run tests
      - name: Run pytest
        run: poetry run pytest -v
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
