name: Dockerized FastAPI Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker (already available in GitHub runners, but keep explicit)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ems:latest .

      # Step 4: List files to verify tests exist
      - name: List tests folder inside container
        run: docker run --rm ems:latest ls -R /app/education_management_system/education_management_system/tests

      # Step 5: Run pytest inside the container
      - name: Run tests inside Docker
        run: docker run --rm ems:latest pytest education_management_system/education_management_system/tests/ -v
